### ISSUE TITLE
?: proper way to handle form validation using this plugin

### ISSUE THREAD

**Issue by Scnck** [shaack/bootstrap-show-modal#10]
Hi,

could you please provide a simple example how to add validation to form inputs within this plugin? Thank  you.

**Comment by shaack** [comment]
Server- or client side validation? You can use the "required" attribute for simple required-validation on client side.

**Comment by Scnck** [comment]
was able to do it looking at client side... Is there a better approach?

```
...
...
...
	onCreate: function (modal) {
		// create event handler for form submit and handle values
		$(modal.element).on("click", "button[type='submit']", function (event) {
			event.preventDefault()
			var $form = $(modal.element).find("form");
			$form[0].reportValidity();
			
			if ($form[0].checkValidity()) {
				modal.hide();
			}
		});
	}
```

**Comment by shaack** [comment]
I think your proposal looks quite good. bootstrap-show-modal is just meant as a bare-bone JS wrapper around the bootstrap functionality of modals. So it is up to you to decide how to make something. The "onCreate" handler is the right place to register button-handlers. Maybe in future versions I will provide some convenience things for button handling.

I have an idea like this:

```
props.buttons = {OK: {text: 'OK', type: 'primary', onClick: function() { /* ok button handling */ }},
cancel: {text: 'Cancel', type: 'secondary', onClick: function() { /* cancel button handling */ }}
}
this.showModal(props)
```

but... future development.
