### ISSUE TITLE
BS5 support

### ISSUE THREAD

**Issue by yahyaerturan** [shaack/bootstrap-show-modal#13]
Are you planning to update library to BS5? I make it work on BS5. Should I send PR or fork the repository?

**Comment by shaack** [comment]
Yes, BS5 should be supported in future. Would be great, if you make a PR for this.

**Comment by yahyaerturan** [comment]
In BS5, accessing and initiating model has changed.  So can not support BS4 and 5 together. Let me know how you will branch this so I will follow. BR

**Comment by shaack** [comment]
@maurojs10 made it bootstrap 5 compatible, thanks.
