### ISSUE TITLE
Bootstrap is not defined. Help please.

### ISSUE THREAD

**Issue by mumus** [shaack/bootstrap-show-modal#21]
bootstrap-show-modal.js:167 Uncaught ReferenceError: bootstrap is not defined
    at ./node_modules/bootstrap-show-modal/src/bootstrap-show-modal.js (bootstrap-show-modal.js:167:2)
    
import * as bootstrap from 'bootstrap';
window.bootstrap = bootstrap;
import 'bootstrap-show-modal';

**Comment by shaack** [comment]
Hi, this looks like a problem with your transpiling software, your code is not standard ES6 syntax.
