### ISSUE TITLE
Dynamic button creation

### ISSUE THREAD

**Issue by JCardonaCTRL** [shaack/bootstrap-show-modal#24]
I think your proposal looks quite good. bootstrap-show-modal is just meant as a bare-bone JS wrapper around the bootstrap functionality of modals. So it is up to you to decide how to make something. The "onCreate" handler is the right place to register button-handlers. Maybe in future versions I will provide some convenience things for button handling.

I have an idea like this:

```
props.buttons = {OK: {text: 'OK', type: 'primary', onClick: function() { /* ok button handling */ }},
cancel: {text: 'Cancel', type: 'secondary', onClick: function() { /* cancel button handling */ }}
}
this.showModal(props)
```

but... future development.

_Originally posted by @shaack in https://github.com/shaack/bootstrap-show-modal/issues/10#issuecomment-668783275_
            

I have been working on migrating another library that I used for BS3, so I have been looking for a compatible for BS5 and I need something similar to what you described.

I changed the way the showModal works to something like this:
```
bootstrap.showModal = (props) => {
    if (props.buttons) {
        let footer = ""
        for (let button in props.buttons) {
            let buttonObj = props.buttons[button]
            , id      = ""
            , text    = ""
            , classed = "btn-default"
            , click   = "";

            if (buttonObj.constructor == Object) {
                id      = buttonObj.id;
                text    = buttonObj.text;
                classed = buttonObj['class'] || buttonObj.classed || classed;
                click   = buttonObj.click;
            } else {
                continue;
            }

            footer += `<button type="button" class="btn ${classed}" id="${id}">${text}</button>`
        }
        props.footer = footer

        props.onCreate = (modal) => {
            for (let button in props.buttons) {
                let buttonObj = props.buttons[button]
                , id      = ""
                , text    = ""
                , classed = "btn-default"
                , click   = "";

                if (buttonObj.constructor == Object) {
                    id      = buttonObj.id;
                    text    = buttonObj.text;
                    classed = buttonObj['class'] || buttonObj.classed || classed;
                    click   = buttonObj.click;
                } else {
                    continue;
                }
                modal.element.querySelector("#"+id).addEventListener("click", click);
            }
        }
    }
    
    return new Modal(props)
}
```
and it will be called like this:

```
buttons: [
                    {
                        id:"btnClose",
                        text: "Close",
                        class: "btn-primary",
                        click: function(modal) {
                            const modalInstance = bootstrap.Modal.getInstance($(this).closest('.modal')[0]);
                            if (modalInstance) {
                                modalInstance.hide()
                            }
                        }
                    }, {
                        id:     "btnSubmit",
                        text:   "Enter",
                        class:  "btn-success",
                        click: function() {
                            if ($("#form").valid()) {                                
                            }
                        }
                    }
                ]
```

One of the difficult parts for me was to get the instance of the modal since at that point the event is outside the modal element, I know there is a better way to do it, do you think it will be possible to add it? And if there could be a way to have an example to validate the form using jQuery-validate it would be even better.

Thanks

**Comment by shaack** [comment]
I am not sure, I understand your request. The instance of the modal is provided as parameter of the event handler: `click: function(modal) {...`. To the jQuery thing, yes, I also used jQuery in former times but nowadays I want to get rid of jQuery and do everything with vanilla JS. Do you know of a form validation framework which does not depend on jQuery and is similar to `jQuery-validate`?

**Comment by JCardonaCTRL** [comment]
Thanks for your answer, the main request is if the dynamic button creation with event handling can be added directly to the library? I did not submit a PR because I know it is not an elegant solution but wanted to show the workaround that worked for me and maybe provide an idea of where to start.

As for the parameter in the event handler, the target is the button that has been clicked:
```
console.log(modal.currentTarget);
<button type="button" class="btn btn-primary" id="btnClose">Close</button>
``` 
It says "modal" because I thought it was going to be the modal object but it wasn't, that's why I had to brute-force it using the `getInstance`.

Unfortunately for HTML5 validation, I don't have a recommendation, I just do the jQuery-validate validations since I still use jQuery for a lot of client-side code.

**Comment by JCardonaCTRL** [comment]
Not sure if this is how you solve the return of the modal instance in the click button, but leaving it in case it helps someone (also a little bit less lines of code):

```
bootstrap.showModal = (props) => {
    if (props.buttons) {
        let footer = ""
        for (let button in props.buttons) {
            let buttonObj = props.buttons[button]
            , id      = ""
            , text    = ""
            , classed = "btn-default"

            if (buttonObj.constructor == Object) {
                id      = buttonObj.id;
                text    = buttonObj.text;
                classed = buttonObj['class'] || buttonObj.classed || classed;
            } else {
                continue;
            }

            footer += `<button type="button" class="btn ${classed}" id="${id}">${text}</button>`
        }
        props.footer = footer

        props.onCreate = (modal) => {
            for (let button in props.buttons) {
                let buttonObj = props.buttons[button]
                , id      = ""
                , click   = "";

                if (buttonObj.constructor == Object) {
                    id      = buttonObj.id;
                    click   = buttonObj.click;
                } else {
                    continue;
                }
                modal.element.querySelector("#"+id).addEventListener("click", () => {
                    click(modal);
                });
            }
        }
    }
    
    return new Modal(props)
}
```

**Comment by shaack** [comment]
Thank you
