### ISSUE TITLE
bootstrap-show-modal and webpack encore - jQuery is not defined 

### ISSUE THREAD

**Issue by SergRad** [shaack/bootstrap-show-modal#9]
Hello Stefan!
I using couple plugin in webpack on start development.
Selec2 plugin work fine.
But after include bootstrap-show-modal from import I get error jQuery is not defined 
![Screenshot_1](https://user-images.githubusercontent.com/6420699/85117032-e04f0d80-b226-11ea-90d6-f177ea9b0ade.png)

Webpack encore main.js : 

// Need jQuery? Install it with "yarn add jquery", then uncomment to import it.
import $ from 'jquery';
import jQuery from 'jquery';

// Bootstrap js
import "bootstrap"

// Plugins JS
import "select2" // work fine
import "bootstrap-show-modal" // get error jQuery is not defined 

// PLUGIN TEST
$.showModal({title: "Hello World!", body: "A very simple modal dialog without buttons."})

**Comment by shaack** [comment]
Did you try / found this? https://github.com/webpack/webpack/issues/4258
